# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/workspace/demo/demo.cache/wt [current_project]
set_property parent.project_path D:/workspace/demo/demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/workspace/p/ip [current_project]
add_files D:/workspace/demo/ahri0.coe
add_files D:/workspace/demo/ahri1.coe
add_files D:/workspace/demo/syndra0.coe
add_files D:/workspace/demo/syndra1.coe
add_files D:/workspace/demo/home.coe
read_ip D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all d:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]
set_property is_locked true [get_files D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci]

read_ip D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all d:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]
set_property is_locked true [get_files D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci]

read_ip D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all d:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]
set_property is_locked true [get_files D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci]

read_ip D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

read_ip D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/workspace/demo/demo.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci]

read_ip D:/workspace/demo/demo.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.xci
set_property is_locked true [get_files D:/workspace/demo/demo.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.xci]

read_verilog -library xil_defaultlib {
  D:/workspace/demo/demo.srcs/sources_1/imports/p/OnePulse.v
  D:/workspace/demo/demo.srcs/sources_1/imports/demo1/vga.v
  {D:/workspace/demo/demo.srcs/sources_1/imports/Unit9_demo2_music box/PWM.v}
  {D:/workspace/demo/demo.srcs/sources_1/imports/Unit9_demo2_music box/PlayerCtrl.v}
  {D:/workspace/demo/demo.srcs/sources_1/imports/Unit9_demo2_music box/Music.v}
  D:/workspace/demo/demo.srcs/sources_1/imports/demo1/clock_divisor.v
  D:/workspace/demo/demo.srcs/sources_1/imports/demo1/pixel_gen.v
  D:/workspace/demo/demo.srcs/sources_1/imports/p/KeyboardDecoder.v
  D:/workspace/demo/demo.srcs/sources_1/imports/demo1/top.v
}
read_xdc D:/workspace/demo/demo.srcs/constrs_1/imports/demo1/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/workspace/demo/demo.srcs/constrs_1/imports/demo1/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
